In [27]:
import json
import pandas as pd

with open("data/par-to-par-enriched.json", "r", encoding="utf-8") as f:
    data = json.load(f)           # dict: {case_id: {...}, ...}

In [28]:
df = pd.read_excel("data/par-to-par-2.xlsx")

for col in ["DATE_FROM", "DATE_TO"]:
    df[col] = pd.to_datetime(df[col], errors="coerce")

df.head()

,CELEX_FROM,TITLE_FROM,NUMBER_FROM,DATE_FROM,TEXT_FROM,CELEX_TO,TITLE_TO,NUMBER_TO,TEXT_TO,DATE_TO
0,61985CJ0341,Erik van der Stijl and Geoffrey Cullington v C...,18,1989-02-28,18 Those arguments need not be addressed . As ...,61976CJ0030,Berthold Küster v European Parliament.,8,8 IT CANNOT BE CONTESTED THAT THOSE TO WHOM A ...,1976-11-25
1,61985CJ0341,Erik van der Stijl and Geoffrey Cullington v C...,51,1989-02-28,51 The Court held in its judgment of 30 Octobe...,61973CJ0188,Daniele Grassi v Council of the European Commu...,38,"38 IN FACT, THOUGH THE APPOINTING AUTHORITY HA...",1974-10-30
2,61986CJ0062,AKZO Chemie BV v Commission of the European Co...,16,1991-07-03,"16 In that respect it should be observed that,...",61982CJ0043,Vereniging ter Bevordering van het Vlaamse Boe...,25,25 IN THAT CONNECTION IT MUST BE OBSERVED THAT...,1984-01-17
3,61986CJ0062,AKZO Chemie BV v Commission of the European Co...,51,1991-07-03,51 In its judgment in Case 31/80 L' Oréal v De...,61980CJ0031,"NV L'Oréal and SA L'Oréal v PVBA ""De Nieuwe AM...",25,25 AS THE COURT EMPHASIZED IN ITS JUDGMENT OF ...,1980-12-11
4,61986CJ0062,AKZO Chemie BV v Commission of the European Co...,60,1991-07-03,60 With regard to market shares the Court has ...,61976CJ0085,Hoffmann-La Roche & Co. AG v Commission of the...,41,41FURTHERMORE ALTHOUGH THE IMPORTANCE OF THE M...,1979-02-13

In [47]:
# Get unique CELEX_FROM and CELEX_TO in df as one list
case_ids = list(set(df["CELEX_FROM"].unique().tolist() + df["CELEX_TO"].unique().tolist()))
empty_cases = [case_id for case_id in case_ids if not data.get(case_id, {}).get("meta", {}).get("sections", [])]
non_empty_cases = [case_id for case_id in case_ids if case_id not in set(empty_cases)]
len(empty_cases) / len(case_ids)

0.6325554705432288

In [ ]:
df[df["CELEX_TO"].isin(non_empty_cases)].sort_values(by="NUMBER_TO", ascending=True)

,CELEX_FROM,TITLE_FROM,NUMBER_FROM,DATE_FROM,TEXT_FROM,CELEX_TO,TITLE_TO,NUMBER_TO,TEXT_TO,DATE_TO
15949,62003CJ0230,Mehmet Sedef v Freie und Hansestadt Hamburg.,48,2006-01-10,48. It is in order to temper the severity of t...,61995CJ0171,Recep Tetik v Land Berlin.,1,"1 By order of 11 April 1995, received at the C...",1997-01-23
2155,61993CJ0444,Ursula Megner and Hildegard Scheffel v Innungs...,20,1995-12-14,20 It should be observed in that connection th...,61963CJ0075,Mrs M.K.H. Hoekstra (née Unger) v Bestuur der ...,1,1 . THE QUESTION PUT BY THAT COURT REQUESTS TH...,1964-03-19
25919,62006CJ0491,Danske Svineproducenter v Justitsministeriet.,22,2008-05-08,"22. Furthermore, Article 234 EC establishes di...",61971CJ0006,Rheinmühlen Düsseldorf v Einfuhr- und Vorratss...,1,"1 BY ORDER DATED 15 DECEMBER 1970, RECEIVED AT...",1971-10-27
30402,62008CJ0115,Land Oberösterreich v ČEZ as.,84,2009-10-27,"84. Moreover, the Court, under Articles 234 EC...",61984CJ0044,Derrick Guy Edmund Hurd v Kenneth Jones (Her M...,1,"1 BY A DECISION OF 14 FEBRUARY 1984 , WHICH WA...",1986-01-15
74456,62006CJ0006,"Cofradía de pescadores ""San Pedro"" de Bermeo a...",39,2007-11-22,"39. À cet égard, force est de constater que ce...",61995CJ0179,Kingdom of Spain v Council of the European Union.,1,1 By application lodged at the Court on 9 June...,1999-10-05
...,...,...,...,...,...,...,...,...,...,...
71448,62009CJ0272,"KME Germany AG, KME France SAS and KME Italy S...",103,2011-12-08,103. The review of legality is supplemented by...,61999CJ0238,Limburgse Vinyl Maatschappij NV (LVM) (C-238/9...,692,"692 In that regard, it is sufficient to point ...",2002-10-15
89311,62016CJ0123,Orange Polska SA v European Commission.,106,2018-07-25,"106\n\n\nBy contrast, when they exercise their...",61999CJ0238,Limburgse Vinyl Maatschappij NV (LVM) (C-238/9...,692,"692 In that regard, it is sufficient to point ...",2002-10-15
70793,62007CJ0534,William Prym GmbH & Co. KG and Prym Consumer G...,86,2009-09-03,86. As regards the review carried out by the C...,61999CJ0238,Limburgse Vinyl Maatschappij NV (LVM) (C-238/9...,692,"692 In that regard, it is sufficient to point ...",2002-10-15
71850,62010CJ0386,Chalkor AE Epexergasias Metallon v European Co...,63,2011-12-08,63. The review of legality is supplemented by ...,61999CJ0238,Limburgse Vinyl Maatschappij NV (LVM) (C-238/9...,692,"692 In that regard, it is sufficient to point ...",2002-10-15
71859,62010CJ0389,"KME Germany AG, KME France SAS and KME Italy S...",130,2011-12-08,130. The review of legality is supplemented by...,61999CJ0238,Limburgse Vinyl Maatschappij NV (LVM) (C-238/9...,692,"692 In that regard, it is sufficient to point ...",2002-10-15

In [22]:
section_counts = {}
for case_id in case_ids:
    if case_id in data:
        case = data[case_id]
        if case.get("meta", {}).get("sections"):
            for section in case["meta"]["sections"]:
                if section not in section_counts:
                    section_counts[section] = 0
                section_counts[section] += 1

# Calculate the fraction of each section type
section_fractions = {section: count / len(case_ids) for section, count in section_counts.items()}
section_fractions

{'keywords': 0.36103672532517217,
 'summary': 0.3528117827084927,
 'parties': 0.39680566182096405,
 'subject_of_the_case': 0.09649961744452945,
 'grounds': 0.3961361897475134,
 'decision_on_costs': 0.3633320581484315,
 'operative_part': 0.39680566182096405,
 'full_text': 0.5136763580719205,
 'judgment': 0.06302601377199694,
 'need_help?': 0.02649196633511859,
 'follow_us': 0.02649196633511859,
 'legal': 0.02649196633511859,
 'information': 0.02649196633511859,
 'other_services': 0.02649196633511859,
 'contact_the_eu': 0.02649196633511859,
 'social_media': 0.02649196633511859,
 'eu_institutions': 0.02649196633511859}

In [17]:
empty_cases

[]